
<div class="mainContent-Friend" style="">
    <div style="margin: 0 auto; width: 300px; padding-top: 15px;font-size: 20px;">
        <div style="font-family: 'Terminal Dosis';">
            <span>156 bạn bè, 6 bạn chung.</span>
        </div>

    </div>
    <hr class="hr-friend">
    <div class="list-friend" style=" float: left;">
        <div id="circle" class="ec-circle">
            <a href="#" class="song-tai">Sống tại Vietnam,</a>
            <a href="#" href="" class="ban-chung">có 3 bạn chung</a>
            <a href="#" class="huy-ketban">Hủy kết bạn</a>
        </div>
        <h3 class="friend-link"><a href="#">Nguyễn Phúc Hưng<a/></h3>
    </div>
    <div class="list-friend" style=" float: left;">
        <div id="circle" class="ec-circle">
            <a href="#" class="song-tai">Sống tại Vietnam,</a>
            <a href="#" href="" class="ban-chung">có 3 bạn chung</a>
            <a href="#" class="huy-ketban">Hủy kết bạn</a>
        </div>
        <h3 class="friend-link"><a href="#">Nguyễn Phúc Hưng<a/></h3>
    </div>


</div>
