<style type="text/css">

    .logoZess:hover{
        text-decoration: none;
    }
    .statusType > div {
        cursor: pointer;
    }

</style>

<script type="text/javascript">
    $('body').addClass('bodyUserpage');
    $('html').addClass('bodyUserpage');
</script>

<?php //var_dump($datauser);die(); ?>

<input type="hidden" id="userID" value="<?php echo $datauser->getUserid(); ?>">

<div class="divLeft">
    <div class="divSubMenu">
        <a class="logoZess" style="width: 100%;" href="<?php echo $this->basePath(); ?>/">
<!--            <div class="divLogo">ZESS</div>-->
            <div style="padding: 10px 0px 5px 50px; width: 100%;">
                <img style="width: 60%;height: 60%;" src="<?php echo $this->basePath();?>/img/zess_logo2.png">
            </div>
        </a>
        <div class="divSearch">
            <form action="#">
                <input id="txtSearch" type="text" placeholder="Search ..." />
                <input id="btnSearch" type="submit" value=" " />
            </form>
        </div>
        <div class="divSub about">
            <div class="divHead"> About me </div>
            <div class="divContent">
                <div class="aboutImg job">
                </div>
                <div class="aboutInfo">
                    <?php
                        if($datauser->getSchool() != null)
                        {
                            echo $datauser->getSchool();
                        }
                        else
                        {
                            echo "Chưa cập nhật.";
                        }
                    ?>
                </div>
            </div>
            <div class="divContent">
                <div class="aboutImg study">
                </div>
                <div class="aboutInfo">
                    <?php
                    if($datauser->getWork() != null)
                    {
                        echo $datauser->getWork();
                    }
                    else
                    {
                        echo "Chưa cập nhật";
                    }
                    ?>
                </div>
            </div>
            <div class="divContent">
                <div class="aboutImg relationship">
                </div>
                <div class="aboutInfo">
                    <?php
                    if($datauser->getRelationship() != null)
                    {
                        echo $datauser->getRelationship();
                    }
                    else
                    {
                        echo "Chưa cập nhật.";
                    }
                    ?>
                </div>
            </div>
        </div>
        <div class="divSub friend">
            <div class="divHead"> Friend </div>
            <div class="divContent">
                <?php
                for ($i = 0; $i < 12; $i++){
                    echo '<div class="subImage"></div>';
                }
                ?>
            </div>
        </div>
        <div class="divSub photo">
            <div class="divHead"> Photos </div>
            <div class="divContent">
                <?php
                for ($i = 0; $i < 12; $i++){
                    echo '<div class="subImage"></div>';
                }
                ?>
            </div>
        </div>
    </div>

    <div class="divMenu">
        <a>
            <div class="menuSub home">
                <div class="divMenuIcon home"></div>
                <div class="divMenuName home">Home</div>
            </div>
        </a>
        <a>
            <div class="menuSub me">
                <div class="divMenuIcon me"></div>
                <div class="divMenuName me">Me</div>
            </div>
        </a>
        <a>
            <div class="menuSub noti">
                <div class="divMenuIcon noti"></div>
                <div class="divMenuName noti">Shake</div>
            </div>
        </a>
        <a href="<?php echo $this->url('success', array('action' => 'friend')); ?>">
            <div class="menuSub friend">
                <div class="divMenuIcon friend"></div>
                <div class="divMenuName friend">Friend</div>
            </div>
        </a>
        <a>
            <div class="menuSub mail">
                <div class="divMenuIcon mail"></div>
                <div class="divMenuName mail">Mail</div>
            </div>
        </a>
        <a href="<?php echo $this->url('success', array('action' => 'update-info')); ?>">
            <div class="menuSub config">
                <div class="divMenuIcon config"></div>
                <div class="divMenuName config">Config</div>
            </div>
        </a>
    </div>

    <div class="divUserPanel">
        <div class="userAvatar">
            <img src="<?php echo $this->basePath().'/uploads/'.$pathUserAvatar; ?>" id="userAvatar" />
        </div>
        <div class="userInfo">
            <div class="info name"><?php echo $datauser->getLastname() .' '. $datauser->getFirstname(); ?></div>
            <div class="info age">
                <div class="infoIcon age"></div>
                <div class="infoContent age">
                    <?php
                        if($datauser->getDOB() != null)
                        {
                            $date = new DateTime($datauser->getDOB());
                            echo date_format($date, 'd-m-Y');
                        }
                        else
                        {
                            echo "Chưa cập nhật.";
                        }
                    ?>
                </div>
            </div>
            <div class="info address">
                <div class="infoIcon address"></div>
                <div class="infoContent address">
                    <?php
                        if($datauser->getAddress() != null)
                        {
                            echo $datauser->getAddress();
                        }
                        else
                        {
                            echo "Chưa cập nhât.";
                        }
                    ?>
                </div>
            </div>
            <div class="info quote">
                <div class="infoIcon quote"></div>
                <div class="infoContent quote">
                    <?php
                        if($datauser->getQuote() != null)
                        {
                            echo $datauser->getQuote();
                        }
                        else
                        {
                            echo "Chưa cập nhật";
                        }
                    ?>
                </div>
            </div>
            <div class="logOut">
                <div class="infoIcon logout"></div>
                <a href="<?php echo $this->url('success', array('action' => 'logout')); ?>" style="color: white;"><div class="infoContent logout">Log Out</div></a>
            </div>
        </div>
    </div>
</div>


<div class="divRight">
    <div class="divCover">
        <img id="imgCover" src="<?php echo $this->basePath().'/uploads/'.$pathCover; ?>" />
    </div>
    <div class="statusBlock">
        <div class="statusType">
            <div id="clickStatus" style="cursor: pointer;" class="type normal">Trạng thái</div>
            <div id="clickShare" class="type share">Chia sẻ</div>
            <div id="clickImage" class="type image">Đăng Ảnh</div>
            <div id="clickVideo" class="type video">Đăng Video</div>
        </div>
        <div class="statusContent">

            <div class="clickStatus" style="display: block;">
                <form action="" method="post" id="formSubStatus">
                    <div class="statusComposeArea">
                        <textarea name="contentStatus" id="statusPostContent" placeholder="Nhập vào trạng thái của bạn... "></textarea>
                    </div>
                    <div class="btnSubmit">
                        <input id="btnPost" class="postStatus" type="submit" value="Feel" />
                    </div>
                </form>
            </div>

            <div class="clickShare" style="display: none;">
                <div class="statusComposeArea">
                    <textarea>Day la Share</textarea>
                </div>
                <div class="btnSubmit">
                    <input id="btnPost" type="button" value="Feel" />
                </div>
            </div>

            <div class="clickImage" style="display: none;">
                <div class="statusComposeArea">
                    <textarea>Day la Image</textarea>
                </div>
                <div class="btnSubmit">
                    <input id="btnPost" type="button" value="Feel" />
                </div>
            </div>

            <div class="clickVideo" style="display: none;">
                <div class="statusComposeArea">
                    <textarea>Day la Video</textarea>
                </div>
                <div class="btnSubmit">
                    <input id="btnPost" type="button" value="Feel" />
                </div>
            </div>

        </div>

    </div>

    <?php
    $stt = 0;
    foreach($idAllContent as $id)
    {

    ?>

    <div class="divAction">
        <div class="divStatus">
            <div class="statusAvatar">
                <img src="<?php echo $this->basePath().'/uploads/'.$pathUserAvatar; ?>" />
            </div>
            <div class="statusRightPanel">
                <div class="statusPosition">
                    <span>
                        <?php echo $datauser->getLastname() .' '. $datauser->getFirstname(); ?>
                    </span> &curren;
                    <?php
                    echo ' lúc '.date('H', $actionTime[$id]). ' giờ ' ;
                    echo date('i', $actionTime[$id]) . ' phút';
                    echo ' ngày '.date('d/m/Y', $actionTime[$id]);
                    ?>
                </div>
                <div class="statusContent">
                    <?php
                    if(isset($allContentbyID[$id]))
                    {
                        echo $allContentbyID[$id];
                    }
                    elseif(isset($imageContent[$id]))
                    {
                        echo "<img src='" . $this->basePath()."/uploads/".$imageContent[$id];
                    }
                    else
                    {
                        echo "Lỗi xảy ra.";
                    }

                    ?>
                </div>
                <div class="statusFooter">
                    <div class="summary">
                        <a class="like" href="#">Like</a>
                        <a class="comment" href="#">Comment</a>
                        <a class="share" href="#">Share</a>
                    </div>
                    <div class="icon">
                        <a class="like" href="#"></a><span>30</span>
                        <a class="comment" href="#"></a><span>30</span>
                        <a class="share" href="#"></a><span>30</span>
                    </div>
                </div>

                <div class="divComment">

                <?php
                if(isset($listCommentID))
                {
                    foreach($listCommentID as $listID)
                    {
                ?>
                    <div class="commentAction">
                        <div class="commentUserAvatar">
                            <img src="<?php echo $this->basePath(); ?>/img/avatar.jpg" />
                        </div>
                        <div class="commentRight">
                            <div class="commentContent"><div class="commentUserName">Fu Hu</div>
                                <?php
                                    echo $commentContent[$listID];
                                ?>
                            </div>
                            <div class="commentFooter">
                                <div class="commentTime">5 minites ago</div>
                                <div class="commentLike">
                                    <a href="#"> Like</a>
                                    <a href="#" class="number">10</a>
                                </div>
                            </div>
                        </div>
                    </div>
                <?php } } ?>

                    <div class="commentCompose">
                        <div class="commentUserAvatar">
                            <img src="<?php echo $this->basePath().'/uploads/'. $pathUserAvatar;?>"/>
                        </div>
                        <form class="form-subPostCmt" name="<?php echo $actionID[$id]; ?>" id="fCmt<?php echo $actionID[$id]; ?>">
                            <div class="commentRight">
                                <textarea name="cmtContentArea" class="contentPostComment"></textarea>
                            </div>
                            <input type="submit" class="postComment" value="Post" />
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <?php
        $stt++;
        }
    ?>

</div>

<script type="text/javascript">
    function getTimestampNow()
    {
        var datenow = new Date();
        datenow = parseInt(datenow.setFullYear(datenow.getFullYear(), datenow.getMonth(), datenow.getDate())/1000);
        return datenow;
    }
</script>

<script type="text/javascript">
    jQuery(document).ready(function(){
//        var scrollInAction = false;
//        jQuery(window).scroll(function(){
//            if  (jQuery(window).scrollTop() >= (jQuery(document).height() - jQuery(window).height() - 200))
//            {
//                if (scrollInAction)
//                {
//                    return false;
//                }else
//                {
//                    scrollInAction=true;
//                    alert('da toi luc phai load content moi');
//                }
//            }
//        });


        var oldDiv =jQuery('.clickStatus');

        jQuery('.statusType div').each(function(){
            jQuery(this).click(function(){
                var newDiv = jQuery(this).attr('id');
                newDiv = jQuery('.'+newDiv);
                var t = 500;
                if(newDiv.text() != oldDiv.text())
                {
                    oldDiv.animate({
                        opacity: 0,
                        marginBottom:"-=200",
                        marginTop: "+=200px"
                    }, t, function(){
                        jQuery(this).css({'margin-top' : '0px', 'margin-bottom': '0px', 'display' : 'none', 'opacity' : 1});
                    });
//                    newDiv.delay(300).slideDown(600);
                    newDiv.delay(300).slideDown(1000, 'easeOutBounce');
                    oldDiv = newDiv;
                }
            });
        });

    });
</script>

<script type="text/javascript">
    //Phan comment cua user

    jQuery(document).ready(function(){
        jQuery('.form-subPostCmt input.postComment').each(function(){
            jQuery(this).on('click',function(){
                var form = jQuery(this).parent().attr('id');
                var actionid = jQuery('#' + form).attr('name');
                var valueComment = jQuery('form#'+form + ' textarea.contentPostComment').val();

                alert(valueComment);

                checkFormCommentArea(jQuery('#' + form), valueComment, actionid);

            });
        });

        function checkFormCommentArea(form, cmtContent, actionID)
        {
            form.validate({
                errorElement: "p",
                rules: {
                    cmtContentArea : {
                        required:true
                    }
                },
                messages:{
                    cmtContentArea:{
                        required: '*Nhập bình luận của bạn vào đây.'
                    }
                },
                submitHandler : function(){
                    ajaxsaveCommentfromAction(cmtContent, actionID);
                }
            });
        }

        function ajaxsaveCommentfromAction(cmtContent, actionID)
        {
            var timeNow = getTimestampNow();
            var data = "cmtContent="+ cmtContent +"&actionID="+actionID+"&timestamp="+ timeNow;

            jQuery.ajax({
                type: "POST",
                url: "<?php echo $this->url('success', array('action' => 'savecomment')); ?>",
                data: data,
                async:false,
                success: function(data) {
                    alert(data);
                    data = JSON.parse(data);
                    var success = data['success'];
                    if(success == "1")
                    {
                        alert('thanh cong');
                    }
                    else
                    {
                        alert('that bai');

                    }
                },
                error: function() {
                    alert("Hệ thống đang bảo trì, xin hãy thử lại sau một ít phút nữa!");
                }
            });
            return false;
        }

        //phan post comment

        jQuery('.postStatus').click(function(){
            checkFormpostStatus();
        });


        function ajaxSubtmitPostStatus()
        {
            var status = jQuery('#statusPostContent').val();
            var timeNow = getTimestampNow();
//            alert(status);
            var data = "status="+status+"&timestamp="+timeNow;

            jQuery.ajax({
                type: "POST",
                url: "<?php echo $this->url('success', array('action' => 'savestatus')); ?>",
                data: data,
                async:false,
                success: function(data) {
//                    alert(data);
                    data = JSON.parse(data);
                    var success = data['success'];
                    var divError = jQuery('#statusPostContent span');
                    if(success == "1")
                    {
                        divError.html(data['message']);
                        divError.show().delay(4000).fadeOut();

                        instancePostStatus(status, timeNow);
                        var divFirstAction =  jQuery('.statusBlock').next();
                        divFirstAction.css("opacity", 0);
                        divFirstAction.animate({
                            opacity:1
                        },3000, "linear");
                    }
                    else
                    {
//                        alert('that bai');
                        divError.html(data['error']);
                        divError.fadeIn(600).delay(4000).fadeOut();
                    }
                },
                error: function() {
                    alert("Hệ thống đang bảo trì, xin hãy thử lại sau một ít phút nữa!");
                }
            });
            return false;
        }

        function checkFormpostStatus()
        {
            jQuery('#formSubStatus').validate({
                errorElement: "span",
                rules: {
                    contentStatus : {
                        required:true
                    }
                },
                messages:{
                    contentStatus:{
                        required: "*.Cảm xúc của bạn là trống rỗng ?"
                    }
                },
                submitHandler : function(){
                    ajaxSubtmitPostStatus();
                }
            });
        }

        function instancePostStatus(statusContent, timeStamp)
        {
            var showdate = new Date();
            var hour = showdate.getHours();
            var minute = showdate.getMinutes();
            var date = showdate.getDate();
            var month = showdate.getMonth();
            var year = showdate.getFullYear();

            showdate = ' lúc '+hour+' giờ '+minute+' phút ngày '+date+'/'+month+'/'+year;

            var divAction = document.createElement('div');
            divAction.className = 'divAction';

            var divStatus = document.createElement('div');
            divStatus.className='divStatus';

            var divStatusAvatar = document.createElement('div');
            divStatusAvatar.className='statusAvatar';

            var imgDivStatusAvatar = document.createElement('img');
            imgDivStatusAvatar.src='<?php echo $this->basePath().'/uploads/'.$pathUserAvatar; ?>';

            var divStatusRightPanel = document.createElement('div');
            divStatusRightPanel.className='statusRightPanel';

            var divstatusPosition = document.createElement('div');
            divstatusPosition.className='statusPosition';

            var spandivstatusPosition = document.createElement('span');
            spandivstatusPosition.innerHTML='<?php echo $datauser->getLastname() .' '. $datauser->getFirstname(); ?>';
            jQuery(spandivstatusPosition).append("<p style='display: inline-block;color: #333; font-size: 12px;'>&curren; "+showdate+"</p>");

            var divstatusContent = document.createElement('div');
            divstatusContent.className= 'statusContent';
            divstatusContent.innerHTML=statusContent;

            var divstatusFooter = document.createElement('div');
            divstatusFooter.className='statusFooter';

            var divsummary = document.createElement('div');
            divsummary.className='summary';

            var tagaLike = document.createElement('a');
            tagaLike.className='like';
            tagaLike.innerHTML='Like';

            var tagsComment = document.createElement('a');
            tagsComment.className='comment';
            tagsComment.innerHTML='Comment';

            var tagaShare = document.createElement('a');
            tagaShare.className='share';
            tagaShare.innerHTML='Share';

            var divIcon = document.createElement('div');
            divIcon.className='icon';

            var tagaLikeCount = document.createElement('a');
            tagaLikeCount.className='like';
            jQuery(tagaLikeCount).attr('href', '#');

            var spanLikeCount = document.createElement('span');
            jQuery(spanLikeCount).text('30');

            var tagaCommentCount = document.createElement('a');
            tagaCommentCount.className='comment';
            jQuery(tagaCommentCount).attr('href', '#');

            var spanCommentCount = document.createElement('span');
            jQuery(spanCommentCount).text('30');

            var tagaShareCount = document.createElement('a');
            tagaShareCount.className = 'share';
            jQuery(tagaShareCount).attr('href', '#');

            var spanShareCount = document.createElement('span');
            jQuery(spanShareCount).text('30');

            var divComment = document.createElement('div');
            divComment.className='divComment';

            var divcommentCompose = document.createElement('div');
            divcommentCompose.className='commentCompose';

            var divcommentUserAvatar = document.createElement('div');
            divcommentUserAvatar.className='commentUserAvatar';

            var imgcommentUserAvatar = document.createElement('img');
            imgcommentUserAvatar.src='<?php echo $this->basePath().'/uploads/'. $pathUserAvatar;?>';

            var formSubtmit = document.createElement('form');
            formSubtmit.className='form-subPostCmt';
            formSubtmit.id='fCmtACT' + timeStamp;
            jQuery(formSubtmit).attr('name','ACT'+timeStamp );

            var divcommentRight = document.createElement('div');
            divcommentRight.className='commentRight';

            var textareaComment = document.createElement('textarea');
            textareaComment.className='contentPostComment';
            jQuery(textareaComment).attr('name', 'cmtContentArea');

            var postComment = document.createElement('input');
            postComment.className = 'postComment';
            jQuery(postComment).attr('type', 'submit');
            jQuery(postComment).attr('value', 'Post');

            divAction.appendChild(divStatus);
                divStatus.appendChild(divStatusAvatar);
                    divStatusAvatar.appendChild(imgDivStatusAvatar);
                divStatus.appendChild(divStatusRightPanel);
                    divStatusRightPanel.appendChild(divstatusPosition);
                        divstatusPosition.appendChild(spandivstatusPosition);
                    divStatusRightPanel.appendChild(divstatusContent);
                    divStatusRightPanel.appendChild(divstatusFooter);
                        divstatusFooter.appendChild(divsummary);
                            divsummary.appendChild(tagaLike);
                            divsummary.appendChild(tagsComment);
                            divsummary.appendChild(tagaShare);
                        divstatusFooter.appendChild(divIcon);
                            divIcon.appendChild(tagaLikeCount);
                            divIcon.appendChild(spanLikeCount);
                            divIcon.appendChild(tagaCommentCount);
                            divIcon.appendChild(spanCommentCount);
                            divIcon.appendChild(tagaShareCount);
                            divIcon.appendChild(spanShareCount);

            divStatusRightPanel.appendChild(divComment);
            divComment.appendChild(divcommentCompose);
            divcommentCompose.appendChild(divcommentUserAvatar);
                divcommentUserAvatar.appendChild(imgcommentUserAvatar);
            divcommentCompose.appendChild(formSubtmit);
            formSubtmit.appendChild(divcommentRight);
            divcommentRight.appendChild(textareaComment);
            formSubtmit.appendChild(postComment);

            jQuery(postComment).on('click', function(){
                var value = jQuery(textareaComment).val();
                var timeStamp= getTimestampNow();
                checkFormCommentArea(jQuery(formSubtmit), value, timeStamp);
            });

            jQuery('.statusBlock').after(divAction);
        }

    });
</script>

