<style type="text/css">

    .logoZess:hover{
        text-decoration: none;
    }
    .statusType > div {
        cursor: pointer;
    }

</style>

<script type="text/javascript">
    jQuery('body').addClass('bodyUserpage');
    jQuery('html').addClass('bodyUserpage');
</script>


<?php

// Time Difference
function time_difference($date)
{
 if(empty($date)) {
 return "unidentifed";
 }
 $periods = array("giây", "phút", "giờ", "ngày", "tuần", "tháng", "năm", "thập kỷ");
 $lengths = array("60","60","24","7","4.35","12","10");
 $now = time();
// $unix_date = strtotime($date);
 $unix_date = $date;
 // Check validity of date

 if(empty($unix_date)) {
 return "Bad date";

 }
 // Determine tense of date

 if($now > $unix_date) {
 $difference = $now - $unix_date;
 $tense = "trước"; } else {
 $difference = $unix_date - $now;
 $tense = "vừa mới";
 }
 for($j = 0; $difference >= $lengths[$j] && $j < count($lengths)-1; $j++) {
 $difference /= $lengths[$j];
 }

 $difference = round($difference);

 if($difference != 1) {
   $periods[$j].= " ";
   }
  return "$difference $periods[$j] {$tense}";
}

//$date = 1387114483;
//$result = time_difference($date);
//echo $result;
//die();

?>


<input type="hidden" id="userID" value="<?php echo $datauser->getUserid(); ?>">

<div class="divLeft">
    <div class="divSubMenu">
        <a class="logoZess" style="width: 100%;" href="<?php echo $this->basePath(); ?>/">
<!--            <div class="divLogo">ZESS</div>-->
            <div style="padding: 10px 0px 5px 50px; width: 100%;">
                <img style="width: 60%;height: 60%;" src="<?php echo $this->basePath();?>/img/zess_logo2.png">
            </div>
        </a>
        <div class="divSearch">
            <form action="#">
                <input id="txtSearch" type="text" placeholder="Search ..." />
                <input id="btnSearch" type="submit" value=" " />
            </form>
        </div>
        <div class="divSub about">
            <div class="divHead"> About me </div>
            <div class="divContent">
                <div class="aboutImg job">
                </div>
                <div class="aboutInfo">
                    <?php
                        if($datauser->getSchool() != null)
                        {
                            echo $datauser->getSchool();
                        }
                        else
                        {
                            echo "Chưa cập nhật.";
                        }
                    ?>
                </div>
            </div>
            <div class="divContent">
                <div class="aboutImg study">
                </div>
                <div class="aboutInfo">
                    <?php
                    if($datauser->getWork() != null)
                    {
                        echo $datauser->getWork();
                    }
                    else
                    {
                        echo "Chưa cập nhật";
                    }
                    ?>
                </div>
            </div>
            <div class="divContent">
                <div class="aboutImg relationship">
                </div>
                <div class="aboutInfo">
                    <?php
                    if($datauser->getRelationship() != null)
                    {
                        echo $datauser->getRelationship();
                    }
                    else
                    {
                        echo "Chưa cập nhật.";
                    }
                    ?>
                </div>
            </div>
        </div>
        <div class="divSub friend">
            <div class="divHead"> Friend </div>
            <div class="divContent">
                <?php
                for ($i = 0; $i < 12; $i++){
                    echo '<div class="subImage"></div>';
                }
                ?>
            </div>
        </div>
        <div class="divSub photo">
            <div class="divHead"> Photos </div>
            <div class="divContent">
                <?php
                for ($i = 0; $i < 12; $i++){
                    echo '<div class="subImage"></div>';
                }
                ?>
            </div>
        </div>
    </div>

    <div class="divMenu">
        <a>
            <div class="menuSub home">
                <div class="divMenuIcon home"></div>
                <div class="divMenuName home">Home</div>
            </div>
        </a>
        <a>
            <div class="menuSub me">
                <div class="divMenuIcon me"></div>
                <div class="divMenuName me">Me</div>
            </div>
        </a>
        <a>
            <div class="menuSub noti">
                <div class="divMenuIcon noti"></div>
                <div class="divMenuName noti">Shake</div>
            </div>
        </a>
<!--        <a href="--><?php //echo $this->url('success', array('action' => 'friend')); ?><!--">-->
        <a href="#">
            <div class="menuSub friend">
                <div class="divMenuIcon friend"></div>
                <?php
                if($getNotifFriend != null && $getNotifFriend > 0)
                {
                ?>
                <div class="divMenuName friend" id="menuFriend" data-notifications="<?php echo $getNotifFriend;?>">Friend</div>

                <?php
                }
                else
                {
                ?>
                    <div class="divMenuName friend" id="menuFriend" >Friend</div>
                <?php
                }
                ?>
                <div class="arrow_box" style=" position: relative; display: none;">
                    <div>
                        <img src="">
                    </div>
                </div>
            </div>
        </a>
        <a>
            <div class="menuSub mail">
                <div class="divMenuIcon mail"></div>
                <div class="divMenuName mail">Mail</div>
            </div>
        </a>
        <a href="<?php echo $this->url('success', array('action' => 'update-info')); ?>">
            <div class="menuSub config">
                <div class="divMenuIcon config"></div>
                <div class="divMenuName config">Config</div>
            </div>
        </a>
    </div>

    <div class="divUserPanel">
        <div class="userAvatar">
            <img src="<?php echo $this->basePath().'/uploads/'.$bigAvatar; ?>" id="userAvatar" />
        </div>
        <div class="userInfo">
            <div class="info name" id="avai-userid" name="<?php echo $actionUserID; ?>">
                <?php echo $datauser->getLastname() .' '. $datauser->getFirstname(); ?>
            </div>
            <div style="display: none" id="actionLocation" name="<?php echo $actionLocationID; ?>"></div>
            <div class="info age">
                <div class="infoIcon age"></div>
                <div class="infoContent age">
                    <?php
                        if($datauser->getDOB() != null)
                        {
                            $date = new DateTime($datauser->getDOB());
                            echo date_format($date, 'd-m-Y');
                        }
                        else
                        {
                            echo "Chưa cập nhật.";
                        }
                    ?>
                </div>
            </div>
            <div class="info address">
                <div class="infoIcon address"></div>
                <div class="infoContent address">
                    <?php
                        if($datauser->getAddress() != null)
                        {
                            echo $datauser->getAddress();
                        }
                        else
                        {
                            echo "Chưa cập nhât.";
                        }
                    ?>
                </div>
            </div>
            <div class="info quote">
                <div class="infoIcon quote"></div>
                <div class="infoContent quote">
                    <?php
                        if($datauser->getQuote() != null)
                        {
                            echo $datauser->getQuote();
                        }
                        else
                        {
                            echo "Chưa cập nhật";
                        }
                    ?>
                </div>
                <?php

//                var_dump($checkFriend);die();
                if($checkFriend == "HOME")
                {
                }
                elseif($checkFriend == "ACCEPTED")
                {
                ?>
                    <a href="#" style="margin-top:30px; " class="a-btn" id="unFriend">
						<span class="a-btn-text">+</span>
						<span class="a-btn-slide-text">Unfriend</span>
						<span class="a-btn-icon-right"><span></span></span>
					</a>

                <?php
                }
                else
                {
                ?>
                    <a href="#" style="margin-top:30px; " class="a-btn" id="addFriend">
                        <span class="a-btn-text">+</span>
                        <span class="a-btn-slide-text">
                            <?php
                            if($checkFriend == "SENT")
                            {
                                echo "Đã gửi";
                            }
                            elseif($checkFriend == "WAITTING")
                            {
                                echo "Đang chờ";
                            }
                            else
                                echo "Kết bạn";
                            ?>
                        </span>
                        <span class="a-btn-icon-right"><span></span></span>
                    </a>
                <?php
                }

                ?>
                </div>
            <div class="logOut">
                <div class="infoIcon logout"></div>
                <a href="<?php echo $this->url('success', array('action' => 'logout')); ?>" style="color: white;"><div class="infoContent logout">Log Out</div></a>
            </div>
        </div>
    </div>
</div>


<div class="divRight">
    <div class="divCover">
        <img id="imgCover" src="<?php echo $this->basePath().'/uploads/'.$imageCover; ?>" />
    </div>
    <?php
    if($checkFriend == "ACCEPTED" or $checkFriend =="HOME")
    {


    ?>

    <div class="statusBlock">
        <div class="statusType">
            <div id="clickStatus" style="cursor: pointer;" class="type normal">Trạng thái</div>
            <div id="clickShare" class="type share">Chia sẻ</div>

            <?php
            if($checkFriend == "HOME")
            {
            ?>
            <div id="clickImage" class="type image">Đăng Ảnh</div>
            <div id="clickVideo" class="type video">Đăng Video</div>

            <?php
            }
            ?>

        </div>
        <div class="statusContent">

            <div class="clickStatus" style="display: block;">
                <form action="" method="post" id="formSubStatus">
                    <div class="statusComposeArea">
                        <textarea name="contentStatus" id="statusPostContent" placeholder="Nhập vào trạng thái của bạn... "></textarea>
                    </div>
                    <div class="btnSubmit">
                        <input id="btnPost" class="postStatus" type="submit" value="Feel" />
                    </div>
                </form>
            </div>

            <div class="clickShare" style="display: none;">
                <form method="post" id="form-postShare"  enctype="multipart/form-data">
                    <div class="statusComposeArea">
                        <div class="place-image">
                            <input class="hide-btn" type="button">
                            <input type="file" id="btnLoadShare" name="image" accept="image/*"/>
                        </div>
                        <div class="place-name">
                            <input type="text" class="txt-place-name" name="placeName" id="placeName" placeholder="Tên địa điểm bạn muốn chia sẻ...">
                        </div>
                        <div class="place-description">
                            <textarea id="descriptPlace" name="descriptPlace" class="txt-place-des" placeholder="Bạn hãy mô tả về địa điểm của mình ..."></textarea>
                        </div>

                    </div>
                    <div class="btnSubmit">
                        <input id="btnPost" class="postShare" type="submit" value="Feel" />
                    </div>
                </form>
            </div>

            <div class="clickImage" style="display: none;">
                <form method="post" action=""
                      id="form-postImage" name="form-postImage" enctype="multipart/form-data">
                    <div class="statusComposeArea">
                        <input type="text" class="descriptImage" name="descriptImage" placeholder="Nhập bình luận của bạn về ảnh này..."/>
                        <input type="file" class="btnLoadImage" id="btnLoadImage" name="image" accept="image/*"/>
                    </div>
                    <div class="btnSubmit">
                        <input id="btnPost" class="postImage" type="submit" value="Đăng Ảnh" />
                    </div>
                </form>
            </div>

            <div class="clickVideo" style="display: none;">
                <form method="post" action="" id="form-postVideo" name="form-postVideo" enctype="multipart/form-data">
                    <div class="statusComposeArea">
                        <input type="text" class="descriptVideo" name="descriptVideo" placeholder="Nhập bình luận của bạn về video này..." />
                        <input type="file" class="btnLoadVideo" id="btnLoadVideo" name="video" accept="video/*" />

                    </div>
                    <div class="btnSubmit">
                        <input id="btnPost" class="postVideo" type="submit" value="Đăng Video" />
                    </div>
                </form>
            </div>
        </div>
    </div>

    <?php
    }
    ?>

<!--  moi them vao  -->
<!--    <div class="scroll-now" style="overflow: scroll; height: 800px; width: 100%;">-->
    <?php
    function getFullTime($date)
    {
        $value  = ' lúc '.date('H', $date). ' giờ ';
        $value .= date('i', $date) . ' phút';
        $value .= ' ngày '.date('d/m/Y', $date);
        return $value;
    }
    arsort($arrayTrueActionID);
    foreach($arrayTrueActionID as $actionID)
    {
        $isOnAnotherWall = false;
        $checkUser  =  $arrayActuserAclocation[$actionID]['actionUser'];
        $checkLocation  =  $arrayActuserAclocation[$actionID]['actionLocation'];
        if($checkUser != $checkLocation)
        {
            $isOnAnotherWall = true;
        }

//        var_dump($arrayActuserAclocation); die();
    ?>
    <div class="divAction">
        <div class="divStatus">
            <div class="statusAvatar">
                <img src="
                <?php
                    echo $this->basePath().'/uploads/'. $infoUseronWal[$checkUser]['pathAvatar'];
                ?>
                " />
            </div>
            <div class="statusRightPanel">
                <div class="statusPosition">
                    <span>
                        <?php
                        echo $infoUseronWal[$checkUser]['fullname'];
                        ?>
                    </span> &curren;
                    <?php
                    echo getFullTime($arrayActionCreatedTime[$actionID]);
                    ?>
                </div>
                <div class="statusContent">
                    <?php
//                    var_dump($arrayActionType); die();
                    $statusID = $arrayActionType[$actionID];

                    if(substr($statusID,0,3) == "STT")
                    {
                        echo "<pre>".$arrayStatusContent[$statusID]."</pre>";
                    }
                    elseif(substr($statusID,0,3) == "IMG")
                    {
//                        var_dump($arrayPathALLIMAGE) ; die();
                        echo "<pre>".$arrayPathALLIMAGE[$statusID]['content']."</pre>";
                        echo "<img src='".$this->basePath()."/uploads/". $arrayPathALLIMAGE[$statusID]['path']."'/>";
                    }
                    elseif(substr($statusID,0,3) == "VID")
                    {
                        echo "<pre>".$arrayPathALLVIDEO[$statusID]['content']."</pre>";
                        $pathViddeo = $arrayPathALLVIDEO[$statusID]['path'];
                        $typteVideo = substr($pathViddeo, -3, 3);

                    ?>

                    <video id="example_video_1" class="video-js vjs-default-skin" controls preload="none" width="100%" height="375"
                           poster="<?php echo $this->basePath().'/img/Logo_Video.png'; ?>"
                           data-setup="{}">
                        <source src="<?php echo $this->basePath().'/uploads/'.$pathViddeo;?>"
                                type='video/<?php echo $typteVideo ?>'>
                    </video>

                    <?php

                    }
                    else{

                    ?>

                        <div class="statusContent">
                        <div class="status-place-image">
                            <img src="<?php echo $this->basePath().'/uploads/'.$arrayALLSharePlace[$statusID]['pathImage']?>">
                        </div>
                        <div class="status-place-name">
                            <span class="name"><?php echo $arrayALLSharePlace[$statusID]['placeName']; ?></span><br>
                            <span class="hashtag"><?php echo $arrayALLSharePlace[$statusID]['hashTag']; ?></span>
                        </div>
                        <div class="status-place-des">
                            <pre><?php echo $arrayALLSharePlace[$statusID]['placeDescription']; ?></pre>
                        </div>
                    </div>

                    <?php
                    }

                    ?>
                </div>
                <div class="statusFooter">
                    <div class="summary" >
                        <a class="like" name="<?php echo $actionID; ?>" style="cursor: pointer;" >Like</a>
                        <a class="comment" href="javascript:void(0)">Comment</a>
                        <a class="share" href="javascript:void(0)">Share</a>
                    </div>
                    <div class="icon">
                        <a class="like" href="javascript:void(0)"></a><span>30</span>
                        <a class="comment" href="javascript:void(0)"></a><span>30</span>
                        <a class="share" href="javascript:void(0)"></a><span>30</span>
                    </div>
                </div>
                <div class="divComment" >
                <?php
                $names = $allCommentID;

                usort($allCommentID, function($a, $b) {
                    $a = substr($a, -10, 10);
                    $b = substr($b, -10, 10);
                    return strcmp($a, $b);
                });

                foreach($allCommentID as $comentid)
                {

                    if(isset($arrayCommentContent[$actionID][$comentid]))
                    {
//                        var_dump($allCommentID);die();

                ?>
                    <div class="commentAction">
                        <div class="commentUserAvatar">
                            <img src="<?php echo $this->basePath().'/uploads/'.$infoUserCommented[$comentid]['pathAvatar'].'"' ?>">
                        </div>
                        <div class="commentRight">
                            <div class="commentContent"><div class="commentUserName">
                                    <?php echo $infoUserCommented[$comentid]['fullname']; ?>
                                </div>
                                <?php
                                    echo $arrayCommentContent[$actionID][$comentid];
                                ?>
                            </div>
                            <div class="commentFooter">
                                <div class="commentLike">
                                    <a href="#"> Like</a>
                                    <a href="#" class="number">10</a>
                                </div>
                                <div class="commentTime" title="<?php
                                $dateComment =  substr($comentid, -10,10);
                                echo getFullTime($dateComment);

                                ?>">
                                <?php
                                    echo time_difference($dateComment);
                                ?>
                                </div>
                            </div>
                        </div>
                    </div>
                <?php
                    }
                }

                if($checkFriend == "ACCEPTED" or $checkFriend == "HOME")
                {
                ?>
                    <div class="commentCompose" id="placeNewCMT_<?php echo $actionID; ?>">
                        <div class="commentUserAvatar">
                            <img src="<?php echo $this->basePath().'/uploads/'. $smallAvatar;  ?>"/>
                        </div>
                        <form class="form-subPostCmt" name="<?php echo $actionID; ?>" id="fCmt<?php echo $actionID; ?>">
                            <div class="commentRight">
                                <textarea name="cmtContentArea" class="contentPostComment"></textarea>
                            </div>
                            <input type="submit" class="postComment" value="Post" />
                        </form>
                    </div>
                    <?php
                }
                    ?>
                </div>
            </div>
        </div>
    </div>

    <?php

        }
    ?>
        <!--   moi them vao     -->
<!--        </div>-->

</div>

<script type="text/javascript">
    function getTimestampNow()
    {
        var datenow = new Date();
        datenow = parseInt(datenow.setFullYear(datenow.getFullYear(), datenow.getMonth(), datenow.getDate())/1000);
        return datenow;
    }
</script>

<script type="text/javascript">
    jQuery(document).ready(function(){

        var oldDiv =jQuery('.clickStatus');

        jQuery('.statusType div').each(function(){
            jQuery(this).click(function(){
                var newDiv = jQuery(this).attr('id');
                newDiv = jQuery('.'+newDiv);
                var t = 500;
                if(newDiv.text() != oldDiv.text())
                {
                    oldDiv.slideUp(1000, 'easeInBounce');
                    newDiv.slideDown(1000, 'easeOutBounce');
                    oldDiv = newDiv;
                }
            });
        });

        jQuery('.form-subPostCmt input.postComment').each(function(){
            jQuery(this).on('click',function(){
                var form = jQuery(this).parent().attr('id');
                var actionIDforCMT = jQuery(this).parent().attr('name');
                var objForm = "#" + form;
//                var actionIDforCMT = jQuery(objForm).attr('name');

                var valueComment = jQuery('form#'+form + ' textarea.contentPostComment').val();
//                alert(actionIDforCMT);
//                alert(valueComment);
                checkFormCommentArea(jQuery(objForm), valueComment, actionIDforCMT);
            });
        });

        function checkFormCommentArea(form, cmtContent, actionIDforCMT)
        {
//            alert('da vao day');
            form.validate({
                errorElement: "p",
                rules: {
                    cmtContentArea : {
                        required:true
                    }
                },
                messages:{
                    cmtContentArea:{
                        required: '*Nhập bình luận của bạn vào đây.'
                    }
                },
                submitHandler : function(){

                    ajaxsaveCommentfromAction(cmtContent,form, actionIDforCMT);
                }
            });
        }

        function ajaxsaveCommentfromAction(cmtContent, form, actionIDforCMT)
        {
            //timestamp là lúc colick vào postComment
            var timeNow = getTimestampNow();
            var actionUser = jQuery('#avai-userid').attr('name');
            var actionLocation = jQuery('#actionLocation').attr('name');
            var data = "actionUser=" +actionUser+"&actionLocation="+actionLocation+"&cmtContent="+ cmtContent +"&timeCreatedComment="+timeNow + "&actionStatusSave="+actionIDforCMT;
            alert(data);
            jQuery.ajax({
                type: "POST",
                url: "<?php echo $this->url('success', array('action' => 'savecomment')); ?>",
                data: data,
                async:false,
                success: function(data) {
//                    alert(data);
                    data = JSON.parse(data);
                    var success = data['success'];
                    if(success == "1")
                    {
//                        @TODO:
                        instanceShowComment(cmtContent, timeNow, form);
                    }
                    else
                    {
                        alert('Đăng bình luận thất bại. Hãy thử lại sau một ít phút nữa.');

                    }
                },
                error: function() {
                    alert("Hệ thống đang bảo trì, xin hãy thử lại sau một ít phút nữa!");
                }
            });
            return false;
        }

        function instanceShowComment(commentContent, timestamp, form)
        {
            var time = " vài giây trước ";

            var divCommentAction = document.createElement('div');
            divCommentAction.className = "commentAction";

            var divCommentUserAvatar = document.createElement('div');
            divCommentUserAvatar.className = "commentUserAvatar";

            var imgCommentUserAvatar = document.createElement('img');
            jQuery(imgCommentUserAvatar).attr('src', '<?php echo $this->basePath()."/uploads/". $smallAvatar;?>');

            var divCommentRight = document.createElement('div');
            divCommentRight.className='commentRight';

            var divcommentContent = document.createElement('div');
            divcommentContent.className='commentContent';

            var divcommentUserName = document.createElement('div');
            divcommentUserName.className='commentUserName';
            jQuery(divcommentUserName).text('<?php  echo $dataGuest->getLastname() .' '. $dataGuest->getFirstname(); ?>');
            jQuery(divcommentContent).append(commentContent);

            var divcommentFooter = document.createElement('div');
            divcommentFooter.className='commentFooter';

            var divcommentLike = document.createElement('div');
            divcommentLike.className='commentLike';

            var tagaLike = document.createElement('a');
            jQuery(tagaLike).text('Like');

            var tagaCountLike = document.createElement('a');
            tagaCountLike.className="number";
            jQuery(tagaCountLike).text('10');

            var divcommentTime = document.createElement('div');
            divcommentTime.className='commentTime';
            jQuery(divcommentTime).text(time);

            divCommentAction.appendChild(divCommentUserAvatar);
                divCommentUserAvatar.appendChild(imgCommentUserAvatar);

            divCommentAction.appendChild(divCommentRight);
                divCommentRight.appendChild(divcommentContent);
                    divcommentContent.appendChild(divcommentUserName);
                divCommentRight.appendChild(divcommentFooter);
                    divcommentFooter.appendChild(divcommentLike);
                        divcommentLike.appendChild(tagaLike);
                        divcommentLike.appendChild(tagaCountLike);
                    divcommentFooter.appendChild(divcommentTime);


            var actID = form.attr('name');
//            jQuery(form.parent().attr('id')).before(divCommentAction);

            var hung = jQuery("#placeNewCMT_" + actID);
//
//            alert(hung.attr('class'));
//
            hung.before(divCommentAction);
        }

        //phan post comment

        jQuery('.postStatus').click(function(){
            checkFormpostStatus();
        });


        function ajaxSubtmitPostStatus()
        {
            var status = jQuery('#statusPostContent').val();
            var timeNow = getTimestampNow();
            var actionLocation = jQuery('#actionLocation').attr('name');
            var actionUser = jQuery('#avai-userid').attr('name');


            var data = "status="+status+"&timestamp="+timeNow + "&actionUser=" +actionUser+"&actionLocation=" +actionLocation;
            alert(data);

            jQuery.ajax({
                type: "POST",
                url: "<?php echo $this->url('success', array('action' => 'savestatus')); ?>",
                data: data,
                async:false,
                success: function(data) {
//                    alert(data);
                    data = JSON.parse(data);
                    var success = data['success'];
                    var divError = jQuery('#statusPostContent span');
                    if(success == "1")
                    {
                        divError.html(data['message']);
                        divError.show().delay(4000).fadeOut();

                        instancePostStatus(status, timeNow);
                        var divFirstAction =  jQuery('.statusBlock').next();
                        divFirstAction.css("opacity", 0);
                        divFirstAction.animate({
                            opacity:1
                        },3000, "linear");
                    }
                    else
                    {
//                        alert('that bai');
                        divError.html(data['error']);
                        divError.fadeIn(600).delay(4000).fadeOut();
                    }
                },
                error: function() {
                    alert("Hệ thống đang bảo trì, xin hãy thử lại sau một ít phút nữa!");
                }
            });
            return false;
        }

        function checkFormpostStatus()
        {
            jQuery('#formSubStatus').validate({
                errorElement: "span",
                rules: {
                    contentStatus : {
                        required:true
                    }
                },
                messages:{
                    contentStatus:{
                        required: "*.Cảm xúc của bạn là trống rỗng ?"
                    }
                },
                submitHandler : function(){
                    ajaxSubtmitPostStatus();
                }
            });
        }

        function instancePostStatus(statusContent, timeStamp)
        {
            var showdate = new Date();
            var hour = showdate.getHours();
            var minute = showdate.getMinutes();
            var date = showdate.getDate();
            var month = showdate.getMonth();
            var year = showdate.getFullYear();

            showdate = ' lúc '+hour+' giờ '+minute+' phút ngày '+date+'/'+month+'/'+year;

            var divAction = document.createElement('div');
            divAction.className = 'divAction';

            var divStatus = document.createElement('div');
            divStatus.className='divStatus';

            var divStatusAvatar = document.createElement('div');
            divStatusAvatar.className='statusAvatar';

            var imgDivStatusAvatar = document.createElement('img');
            var actionName = 'ACT'+timeStamp;
            imgDivStatusAvatar.src="<?php echo $this->basePath().'/uploads/'.$smallAvatar; ?>";

            var divStatusRightPanel = document.createElement('div');
            divStatusRightPanel.className='statusRightPanel';

            var divstatusPosition = document.createElement('div');
            divstatusPosition.className='statusPosition';

            var spandivstatusPosition = document.createElement('span');
            spandivstatusPosition.innerHTML='<?php echo $dataGuest->getLastname() .' '. $dataGuest->getFirstname(); ?>';
            jQuery(spandivstatusPosition).append("<p style='display: inline-block;color: #333; font-size: 12px;'>&curren; "+showdate+"</p>");

            var divstatusContent = document.createElement('div');
            divstatusContent.className= 'statusContent';
//            jQuery(divstatusContent).innerHTML=statusContent;
            jQuery(divstatusContent).append('<pre>' + statusContent + '</pre>');

            var divstatusFooter = document.createElement('div');
            divstatusFooter.className='statusFooter';

            var divsummary = document.createElement('div');
            divsummary.className='summary';

            var tagaLike = document.createElement('a');
            tagaLike.className='like';
            tagaLike.innerHTML='Like';

            var tagsComment = document.createElement('a');
            tagsComment.className='comment';
            tagsComment.innerHTML='Comment';

            var tagaShare = document.createElement('a');
            tagaShare.className='share';
            tagaShare.innerHTML='Share';

            var divIcon = document.createElement('div');
            divIcon.className='icon';

            var tagaLikeCount = document.createElement('a');
            tagaLikeCount.className='like';
            jQuery(tagaLikeCount).attr('href', 'javascript:void(0)');

            var spanLikeCount = document.createElement('span');
            jQuery(spanLikeCount).text('30');

            var tagaCommentCount = document.createElement('a');
            tagaCommentCount.className='comment';
            jQuery(tagaCommentCount).attr('href', 'javascript:void(0)');

            var spanCommentCount = document.createElement('span');
            jQuery(spanCommentCount).text('30');

            var tagaShareCount = document.createElement('a');
            tagaShareCount.className = 'share';
            jQuery(tagaShareCount).attr('href', 'javascript:void(0)');

            var spanShareCount = document.createElement('span');
            jQuery(spanShareCount).text('30');

            var divComment = document.createElement('div');
            divComment.className='divComment';

            var divcommentCompose = document.createElement('div');
            divcommentCompose.className='commentCompose';
            jQuery(divcommentCompose).attr('id', 'placeNewCMT_ACT'+timeStamp);

            var divcommentUserAvatar = document.createElement('div');
            divcommentUserAvatar.className='commentUserAvatar';

            var imgcommentUserAvatar = document.createElement('img');
            imgcommentUserAvatar.src='<?php echo $this->basePath().'/uploads/'. $smallAvatar;?>';

            var formSubtmit = document.createElement('form');
            formSubtmit.className='form-subPostCmt';
            formSubtmit.id='fCmtACT' + timeStamp;
            jQuery(formSubtmit).attr('name','ACT'+timeStamp );

            var divcommentRight = document.createElement('div');
            divcommentRight.className='commentRight';

            var textareaComment = document.createElement('textarea');
            textareaComment.className='contentPostComment';
            jQuery(textareaComment).attr('name', 'cmtContentArea');

            var postComment = document.createElement('input');
            postComment.className = 'postComment';
            jQuery(postComment).attr('type', 'submit');
            jQuery(postComment).attr('value', 'Post');

            divAction.appendChild(divStatus);
                divStatus.appendChild(divStatusAvatar);
                    divStatusAvatar.appendChild(imgDivStatusAvatar);
                divStatus.appendChild(divStatusRightPanel);
                    divStatusRightPanel.appendChild(divstatusPosition);
                        divstatusPosition.appendChild(spandivstatusPosition);
                    divStatusRightPanel.appendChild(divstatusContent);
                    divStatusRightPanel.appendChild(divstatusFooter);
                        divstatusFooter.appendChild(divsummary);
                            divsummary.appendChild(tagaLike);
                            divsummary.appendChild(tagsComment);
                            divsummary.appendChild(tagaShare);
                        divstatusFooter.appendChild(divIcon);
                            divIcon.appendChild(tagaLikeCount);
                            divIcon.appendChild(spanLikeCount);
                            divIcon.appendChild(tagaCommentCount);
                            divIcon.appendChild(spanCommentCount);
                            divIcon.appendChild(tagaShareCount);
                            divIcon.appendChild(spanShareCount);

            divStatusRightPanel.appendChild(divComment);
            divComment.appendChild(divcommentCompose);
            divcommentCompose.appendChild(divcommentUserAvatar);
                divcommentUserAvatar.appendChild(imgcommentUserAvatar);
            divcommentCompose.appendChild(formSubtmit);
            formSubtmit.appendChild(divcommentRight);
            divcommentRight.appendChild(textareaComment);
            formSubtmit.appendChild(postComment);

            jQuery(postComment).on('click', function(){

                var value = jQuery(textareaComment).val();
//                var timeStamp= getTimestampNow();

//                alert('CommentContent=' + value + 'actionID=' + timeStamp);
                    //ko phai timestamp
                checkFormCommentArea(jQuery(formSubtmit), value,'ACT'+ timeStamp);
            });

            jQuery('.statusBlock').after(divAction);
        }

        jQuery('.postImage').click(function(){
            checkFormPostImage();
        });

        jQuery.validator.addMethod('accept', function () { return true; });

        function checkFormPostImage()
        {
            jQuery('#form-postImage').validate({
                debug: true,
                errorElement: "p",
                rules: {
                    image:{
                        required:true,
                        accept: "image/pjpeg,image/jpeg,image/png,image/gif"
                    }
                },
                messages:{
                    image:{
                        required:"Bạn chưa chọn hình để tải lên!",
                        accept: "jpg|jpeg|png|gif"
                    }
                },
                submitHandler : function(){
                    ajaxUploadImageFromMenu();
                }
            });
        }

        function ajaxUploadImageFromMenu()
        {

            var timeNow = getTimestampNow();
            var descript = jQuery('.descriptImage').val();
            var formdata  = new FormData(jQuery('#form-postImage')[0]);
            var reader = new FileReader();
            var value = reader.readAsDataURL(document.getElementById("btnLoadImage").files[0]);
            var userid = jQuery('#avai-userid').attr('name');

            formdata.append('image', value);
            formdata.append('timestamp', timeNow);
            formdata.append('descript', descript);
            formdata.append('userid', userid);

//            var data = "descript="+ descript +"&actionID="+actionID+"&timestamp="+ timeNow;

            jQuery.ajax({
                type: "POST",
                url: "<?php echo $this->basePath().'/plugin/upload_normal.php' ;?>",
                data: formdata,
                cache: false,
                contentType: false,
                processData: false,
                async:false,
                success: function(data) {
                    if(data!='error')
                    {
                        ajaxSaveImageNormal(userid, timeNow, descript, data);
                    }
                },
                error: function() {
                    alert("Hệ thống đang bảo trì, xin hãy thử lại sau một ít phút nữa!");
                }
            });
            return false;
        }

        function ajaxSaveImageNormal(userid, timstamp, descript, data)
        {
            var dataval = "userid=" + userid+"&createdTime=" + timstamp+"&descript="+descript+"&imageType=" +data;
            jQuery.ajax({
                type: "POST",
                url: "<?php echo $this->url('success', array('action' => 'savenormalimage')); ?>",
                data: dataval,
                async:false,
                success: function(data) {
                    data = JSON.parse(data);
    //                    alert('Đăng ảnh thành công!.');
                    var instanceImage = descript + " <img src='<?php echo $this->basePath();?>" +"/uploads/"+ data["success"] + "'/>";
//                    alert(instanceImage);
                    instancePostStatus(instanceImage, timstamp);
                    var divFirstAction =  jQuery('.statusBlock').next();
                    divFirstAction.css("opacity", 0);
                    divFirstAction.animate({
                        opacity:1
                    },3000, "linear");
                },
                error: function() {
                    alert("Hệ thống đang bảo trì, xin hãy thử lại sau một ít phút nữa!");
                }
            });
            return false;
        }

        //upload video

        jQuery('.postVideo').click(function(){
            jQuery('#form-postVideo').validate({
                errorElement: "p",
                rules: {
                    video:{
                        required:true
                    }
                },
                messages:{
                    video:{
                        required:"Bạn chưa chọn Video để tải lên!"
                    }
                },
                submitHandler : function(){
//                    alert('ajjax thoi');
                    ajaxMoveVideo();
                }
            });
        });

        function ajaxMoveVideo()
        {
            var timeNow = getTimestampNow();
            var descript = jQuery('.descriptVideo').val();
            var formdata  = new FormData(jQuery('#form-postVideo')[0]);
            var reader = new FileReader();
            var value = reader.readAsDataURL(document.getElementById("btnLoadVideo").files[0]);
            var userid = jQuery('#avai-userid').attr('name');
//            alert(userid + descript+timeNow);

            formdata.append('image', value);
            formdata.append('timestamp', timeNow);
            formdata.append('descript', descript);
            formdata.append('userid', userid);

            jQuery.ajax({
                type: "POST",
                url: "<?php echo $this->basePath().'/plugin/upload_video.php' ;?>",
                data: formdata,
                cache: false,
                contentType: false,
                processData: false,
                async:false,
                success: function(data) {
//                    alert(data);
                    if(data!='error')
                    {
                        ajaxSaveVideo(userid, timeNow, descript, data);
                    }
                    else
                    {
                        alert('Video tải lên không đúng định dạng hoặc dung lượng quá lớn!.');
                    }
                },
                error: function() {
                    alert("Hệ thống đang bảo trì, xin hãy thử lại sau một ít phút nữa!");
                }
            });
            return false;
        }

        function ajaxSaveVideo(userid, timeStamp, descript, dataType)
        {
            var dataval = "userid=" + userid+"&createdTime=" + timeStamp+"&descript="+descript+"&videoType=" +dataType;

            jQuery.ajax({
                type: "POST",
                url: "<?php echo $this->url('success', array('action' => 'savevideo')); ?>",
                data: dataval,
                async:false,
                success: function(data) {
//                    alert(data);
                    data = JSON.parse(data);
                    if(data['success'] == 1)
                    {
                        var videoType = dataType.substr(-3,3);
                        var videoName = 'VID'+userid+timeStamp+'.'+videoType;
                        var instanceVideo = descript;
                        instanceVideo += ' <video id="example_video_1" class="video-js vjs-default-skin" controls preload="none" ';
                        instanceVideo += ' width="100%" height="375" poster="<?php echo $this->basePath();?>/img/Logo_Video.png" data-setup="{}"> ';
                        instanceVideo += '  <source src="<?php echo $this->basePath();?>' + '/uploads/'+videoName+ '" ';
                        instanceVideo += ' type="video/'+ videoType+' ">';
                        instanceVideo += ' </video>';

//                        alert(instanceVideo);

                        instancePostStatus(instanceVideo, timeStamp);
                        var divFirstAction =  jQuery('.statusBlock').next();
                        divFirstAction.css("opacity", 0);
                        divFirstAction.animate({
                            opacity:1
                        },3000, "linear");
                    }
                },
                error: function() {
                    alert("Hệ thống đang bảo trì, xin hãy thử lại sau một ít phút nữa!");
                }
            });
            return false;
        }

        jQuery('.postShare').click(function(){
//            alert('da click');
            jQuery('#form-postShare').validate({
                errorElement: "span",
                rules: {
                    share:{
                        required:true
                    },
                    placeName: {
                        required:true
                    },
                    descriptPlace:{
                        required : true
                    }
                },
                messages:{
                    share:{
                        required:"**"
                    },
                    placeName: {
                        required:"**"
                    },
                    descriptPlace:{
                        required : "**"
                    }
                },
                submitHandler : function(){
//                    alert('ajjax thoi');
                    saveImageofShare();
                }
            });
        });

        function saveImageofShare()
        {
            var timeNow = getTimestampNow();
            var placeName = jQuery('#placeName').val();
            var descript = jQuery('#descriptPlace').val();
            var formdata  = new FormData(jQuery('#form-postShare')[0]);
            var reader = new FileReader();
            var value = reader.readAsDataURL(document.getElementById("btnLoadShare").files[0]);
            var actionUser = jQuery('#avai-userid').attr('name');
            var actionLocation = jQuery('#actionLocation').attr('name');
//            alert(userid + descript+timeNow);

            formdata.append('image', value);
            formdata.append('timestamp', timeNow);
            formdata.append('descript', descript);
            formdata.append('placeName', placeName);
            formdata.append('actionUser', actionUser);
            formdata.append('actionLocation', actionLocation);

            jQuery.ajax({
                type: "POST",
                url: "<?php echo $this->basePath().'/plugin/upload_normal.php' ;?>",
                data: formdata,
                cache: false,
                contentType: false,
                processData: false,
                async:false,
                success: function(data) {
//                    alert(data);
                    if(data!='error')
                    {
                        var pathImage = data;
                        alert('thanh cong');
                        ajaxSaveNewSharePlace(actionUser, actionLocation, timeNow, placeName, descript, pathImage);
                    }
                    else
                    {
                        alert('Video tải lên không đúng định dạng hoặc dung lượng quá lớn!.');
                    }
                },
                error: function() {
                    alert("Hệ thống đang bảo trì, xin hãy thử lại sau một ít phút nữa!");
                }
            });
            return false;
        }

        function createHashTag(str)
        {
            str = str.toLowerCase();
            str = str.replace(/à|á|ạ|ả|ã|â|ầ|ấ|ậ|ẩ|ẫ|ă|ằ|ắ|ặ|ẳ|ẵ/g, "a");
            str = str.replace(/è|é|ẹ|ẻ|ẽ|ê|ề|ế|ệ|ể|ễ/g, "e");
            str = str.replace(/ì|í|ị|ỉ|ĩ/g, "i");
            str = str.replace(/ò|ó|ọ|ỏ|õ|ô|ồ|ố|ộ|ổ|ỗ|ơ|ờ|ớ|ợ|ở|ỡ/g, "o");
            str = str.replace(/ù|ú|ụ|ủ|ũ|ư|ừ|ứ|ự|ử|ữ/g, "u");
            str = str.replace(/ỳ|ý|ỵ|ỷ|ỹ/g, "y");
            str = str.replace(/đ/g, "d");
            str = str.replace(/!|\$|\@|%|\^|\*|\(|\)|\+|\=|\<|\>|\?|\/|,|\.|\:|\;|\'| |\"|\&|\#|\[|\]|~|$|-/g, "_");
            //thay doi toan bo cac ki tu la trong chuoi
            str = str.replace(/_+_/g, "_"); //thay the 2 dau __ thanh 1_
            str = str.replace(/^\_+|\_+$/g, ""); // bo ki tu dau va cuoi chuoi
            return '#' +str;
        }

//        alert(createHashTag('- _ Sông cầu _ !@#$%^&*()_+'));

        function ajaxSaveNewSharePlace(actionUser, actionLocation, timeNow, placeName, descript, pathImage)
        {

            var hashTag = createHashTag(placeName);
            var dataval = "actionUser=" + actionUser+ "&actionLocation="+actionLocation+"&createdTime=" + timeNow+"&placeName="+placeName;
            dataval += "&descript="+descript+"&imageType=" +pathImage + "&hashTag=" + hashTag;

            alert(dataval);

            jQuery.ajax({
                type: "POST",
                url: "<?php echo $this->url('success', array('action' => 'saveshareplace')); ?>",
                data: dataval,
                async:false,
                success: function(data) {
                    alert(data);
                    data = JSON.parse(data);
                    var instanceImage = " <img src='<?php echo $this->basePath();?>" +"/uploads/"+pathImage + "'/>";
                    instanceImage +=    "<div class='status-place-name'>";
                    instanceImage +=        "<span class='name'>"+placeName+"</span></br>";
                    instanceImage +=        "<span class='hashtag'>"+hashTag+"</span></br>";
                    instanceImage +=    "</div>";
                    instanceImage += "<div class='status-place-des'><pre>"+descript+"</pre></div>";
                    alert(instanceImage);
                    instancePostStatus(instanceImage, timeNow);
                    var divFirstAction =  jQuery('.statusBlock').next();
                    divFirstAction.css("opacity", 0);
                    divFirstAction.animate({
                        opacity:1
                    },3000, "linear");
                },
                error: function() {
                    alert("Hệ thống đang bảo trì, xin hãy thử lại sau một ít phút nữa!");
                }
            });
            return false;
        }

        //FUNCTION FOR LIKE &SHARE

        jQuery('div.summary > a.like').each(function(){
            var buttonLike = jQuery(this);
            buttonLike.click(function(){
                var actionid = buttonLike.attr('name');
                var timeStamp = getTimestampNow();
                var userid = jQuery('#actionLocation').attr('name');

                if(buttonLike.text() == "Like")
                {
                    setLikeStatus(actionid, timeStamp, userid, buttonLike);
                }
                else
                {
                    buttonLike.text('Like');
                    setUnlikeStatus(actionid, timeStamp, userid, buttonLike);
                }
            });
        });

        //FUNCTION FOR ADD FRIEND
        jQuery('#addFriend').click(function(){
            var actionUser = jQuery('#avai-userid').attr('name');
            var actionLocation = jQuery('#actionLocation').attr('name');
            var friendStatus = "SENT";
            var data = "actionUser=" + actionUser+"&actionLocation=" + actionLocation+ "&friendStatus="+friendStatus;

            jQuery.ajax({
                type: "POST",
                url: "<?php echo $this->url('success', array('action' => 'addfriend')); ?>",
                data: data,
                async:false,
                success: function(data) {
                    alert(data);
                    data = JSON.parse(data);
                    var success = data['success'];
                    if(success == "1")
                    {
                       alert("Yêu cầu kết bạn đã được gửi đi. Bạn hãy chờ xác nhận!");
                    }
                    else
                    {
                        alert('Bạn đã gửi yêu cầu kết bạn, hãy chờ xác nhận từ người này');
                    }
                },
                error: function() {
                    alert("Hệ thống đang bảo trì, xin hãy thử lại sau một ít phút nữa!");
                }
            });
            return false;
        });

        jQuery('#unFriend').click(function(){
            var actionUser = jQuery('#avai-userid').attr('name');
            var actionLocation = jQuery('#actionLocation').attr('name');
            var friendStatus = "ACCEPTED";
            var data = "actionUser=" + actionUser+"&actionLocation=" + actionLocation+ "&friendStatus="+friendStatus;

            jQuery.ajax({
                type: "POST",
                url: "<?php echo $this->url('success', array('action' => 'unfriend')); ?>",
                data: data,
                async:false,
                success: function(data) {
                    alert(data);
                    data = JSON.parse(data);
                    var success = data['success'];
                    if(success == "1")
                    {
                        alert("thanh cong");
                    }
                    else
                    {
                        alert('Bạn đã gửi yêu cầu kết bạn, hãy chờ xác nhận từ người này');
                    }
                },
                error: function() {
                    alert("Hệ thống đang bảo trì, xin hãy thử lại sau một ít phút nữa!");
                }
            });
            return false;
        });

        jQuery('#menuFriend').click(function(){

        });

        function setLikeStatus(actionid, timeStamp, userid, buttonLike)
        {
            var data = "actionid="+ actionid +"&timeStamp="+timeStamp + "&userid="+userid;
            alert(data);
            jQuery.ajax({
                type: "POST",
                url: "<?php echo $this->url('success', array('action' => 'savelikestatus')); ?>",
                data: data,
                async:false,
                success: function(data) {
                    alert(data);
                    data = JSON.parse(data);
                    var success = data['success'];
                    if(success == "1")
                    {
                        buttonLike.text('Unlike');
                    }
                    else
                    {
                        alert('Đăng bình luận thất bại. Hãy thử lại sau một ít phút nữa.');
                    }
                },
                error: function() {
                    alert("Hệ thống đang bảo trì, xin hãy thử lại sau một ít phút nữa!");
                }
            });
            return false;
        }

        function setUnlikeStatus(actionid, timeStamp, userid, buttonLike)
        {

        }



    });
</script>

