<style type="text/css">

    .logoZess:hover{
        text-decoration: none;
    }
    .statusType > div {
        cursor: pointer;
    }

</style>

<script type="text/javascript">
    $('body').addClass('bodyUserpage');
    $('html').addClass('bodyUserpage');
</script>

<?php //var_dump($datauser);die(); ?>

<input type="hidden" id="userID" value="<?php echo $datauser->getUserid(); ?>">

<div class="divLeft">
    <div class="divSubMenu">
        <a class="logoZess" style="width: 100%;" href="<?php echo $this->basePath(); ?>/">
<!--            <div class="divLogo">ZESS</div>-->
            <div style="padding: 10px 0px 5px 50px; width: 100%;">
                <img style="width: 60%;height: 60%;" src="<?php echo $this->basePath();?>/img/zess_logo2.png">
            </div>
        </a>
        <div class="divSearch">
            <form action="#">
                <input id="txtSearch" type="text" placeholder="Search ..." />
                <input id="btnSearch" type="submit" value=" " />
            </form>
        </div>
        <div class="divSub about">
            <div class="divHead"> About me </div>
            <div class="divContent">
                <div class="aboutImg job">
                </div>
                <div class="aboutInfo">
                    <?php
                        if($datauser->getSchool() != null)
                        {
                            echo $datauser->getSchool();
                        }
                        else
                        {
                            echo "Chưa cập nhật.";
                        }
                    ?>
                </div>
            </div>
            <div class="divContent">
                <div class="aboutImg study">
                </div>
                <div class="aboutInfo">
                    <?php
                    if($datauser->getWork() != null)
                    {
                        echo $datauser->getWork();
                    }
                    else
                    {
                        echo "Chưa cập nhật";
                    }
                    ?>
                </div>
            </div>
            <div class="divContent">
                <div class="aboutImg relationship">
                </div>
                <div class="aboutInfo">
                    <?php
                    if($datauser->getRelationship() != null)
                    {
                        echo $datauser->getRelationship();
                    }
                    else
                    {
                        echo "Chưa cập nhật.";
                    }
                    ?>
                </div>
            </div>
        </div>
        <div class="divSub friend">
            <div class="divHead"> Friend </div>
            <div class="divContent">
                <?php
                for ($i = 0; $i < 12; $i++){
                    echo '<div class="subImage"></div>';
                }
                ?>
            </div>
        </div>
        <div class="divSub photo">
            <div class="divHead"> Photos </div>
            <div class="divContent">
                <?php
                for ($i = 0; $i < 12; $i++){
                    echo '<div class="subImage"></div>';
                }
                ?>
            </div>
        </div>
    </div>

    <div class="divMenu">
        <a>
            <div class="menuSub home">
                <div class="divMenuIcon home"></div>
                <div class="divMenuName home">Home</div>
            </div>
        </a>
        <a>
            <div class="menuSub me">
                <div class="divMenuIcon me"></div>
                <div class="divMenuName me">Me</div>
            </div>
        </a>
        <a>
            <div class="menuSub noti">
                <div class="divMenuIcon noti"></div>
                <div class="divMenuName noti">Shake</div>
            </div>
        </a>
        <a href="<?php echo $this->url('success', array('action' => 'friend')); ?>">
            <div class="menuSub friend">
                <div class="divMenuIcon friend"></div>
                <div class="divMenuName friend">Friend</div>
            </div>
        </a>
        <a>
            <div class="menuSub mail">
                <div class="divMenuIcon mail"></div>
                <div class="divMenuName mail">Mail</div>
            </div>
        </a>
        <a href="<?php echo $this->url('success', array('action' => 'update-info')); ?>">
            <div class="menuSub config">
                <div class="divMenuIcon config"></div>
                <div class="divMenuName config">Config</div>
            </div>
        </a>
    </div>

    <div class="divUserPanel">
        <div class="userAvatar">
            <img src="<?php echo $this->basePath().'/uploads/'.$pathUserAvatar; ?>" id="userAvatar" />
        </div>
        <div class="userInfo">
            <div class="info name"><?php echo $datauser->getLastname() .' '. $datauser->getFirstname(); ?></div>
            <div class="info age">
                <div class="infoIcon age"></div>
                <div class="infoContent age">
                    <?php
                        if($datauser->getDOB() != null)
                        {
                            $date = new DateTime($datauser->getDOB());
                            echo date_format($date, 'd-m-Y');
                        }
                        else
                        {
                            echo "Chưa cập nhật.";
                        }
                    ?>
                </div>
            </div>
            <div class="info address">
                <div class="infoIcon address"></div>
                <div class="infoContent address">
                    <?php
                        if($datauser->getAddress() != null)
                        {
                            echo $datauser->getAddress();
                        }
                        else
                        {
                            echo "Chưa cập nhât.";
                        }
                    ?>
                </div>
            </div>
            <div class="info quote">
                <div class="infoIcon quote"></div>
                <div class="infoContent quote">
                    <?php
                        if($datauser->getQuote() != null)
                        {
                            echo $datauser->getQuote();
                        }
                        else
                        {
                            echo "Chưa cập nhật";
                        }
                    ?>
                </div>
            </div>
            <div class="logOut">
                <div class="infoIcon logout"></div>
                <a href="<?php echo $this->url('success', array('action' => 'logout')); ?>" style="color: white;"><div class="infoContent logout">Log Out</div></a>
            </div>
        </div>
    </div>
</div>


<div class="divRight">
    <div class="divCover">
        <img id="imgCover" src="<?php echo $this->basePath().'/uploads/'.$pathCover; ?>" />
    </div>
    <div class="statusBlock">
        <div class="statusType">
            <div id="clickStatus" style="cursor: pointer;" class="type normal">Trạng thái</div>
            <div id="clickShare" class="type share">Chia sẻ</div>
            <div id="clickImage" class="type image">Đăng Ảnh</div>
            <div id="clickVideo" class="type video">Đăng Video</div>
        </div>
        <div class="statusContent">

            <div class="clickStatus" style="display: block;">
                <form action="" method="post" id="formSubStatus">
                    <div class="statusComposeArea">
                        <textarea name="contentStatus" id="statusPostContent" placeholder="Nhập vào trạng thái của bạn... "></textarea>
                    </div>
                    <div class="btnSubmit">
                        <input id="btnPost" class="postStatus" type="submit" value="Feel" />
                    </div>
                </form>
            </div>

            <div class="clickShare" style="display: none;">
                <div class="statusComposeArea">
                    <textarea>Day la Share</textarea>
                </div>
                <div class="btnSubmit">
                    <input id="btnPost" type="button" value="Feel" />
                </div>
            </div>

            <div class="clickImage" style="display: none;">
                <div class="statusComposeArea">
                    <textarea>Day la Image</textarea>
                </div>
                <div class="btnSubmit">
                    <input id="btnPost" type="button" value="Feel" />
                </div>
            </div>

            <div class="clickVideo" style="display: none;">
                <div class="statusComposeArea">
                    <textarea>Day la Video</textarea>
                </div>
                <div class="btnSubmit">
                    <input id="btnPost" type="button" value="Feel" />
                </div>
            </div>

        </div>

    </div>

    <div class="divAction">
        <div class="divStatus">
            <div class="statusAvatar">
                <img src="<?php echo $this->basePath().'/uploads/'.$pathUserAvatar; ?>" />
            </div>
            <div class="statusRightPanel">
                <div class="statusPosition"><span>Nguyễn Xuân Bình</span> &curren; 5 minutes ago at Ho Chi Minh</div>
                <div class="statusContent">
                    Hôm nay trời đẹp quá :)
                </div>
                <div class="statusFooter">
                    <div class="summary">
                        <a class="like" href="#">Like</a>
                        <a class="comment" href="#">Comment</a>
                        <a class="share" href="#">Share</a>
                    </div>
                    <div class="icon">
                        <a class="like" href="#"></a><span>30</span>
                        <a class="comment" href="#"></a><span>30</span>
                        <a class="share" href="#"></a><span>30</span>

                    </div>
                </div>
                <div class="divComment">
                    <div class="commentAction">
                        <div class="commentUserAvatar">
                            <img src="<?php echo $this->basePath(); ?>/img/avatar.jpg" />
                        </div>
                        <div class="commentRight">
                            <div class="commentContent"><div class="commentUserName">Fu Hu</div>Thằng này bị điên rồi =.="</div>
                            <div class="commentFooter">
                                <div class="commentTime">5 minites ago</div>
                                <div class="commentLike">
                                    <a href="#"> Like</a>
                                    <a href="#" class="number">10</a>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="commentCompose">
                        <div class="commentUserAvatar">
                            <img src="<?php echo $this->basePath().'/uploads/'. $pathUserAvatar;?>"/>
                        </div>
                        <div class="commentRight">
                            <textarea></textarea>
                        </div>
                        <input type="button" value="Post" />
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    jQuery(document).ready(function(){

        var oldDiv =jQuery('.clickStatus');

        jQuery('.statusType div').each(function(){
            jQuery(this).click(function(){
                var newDiv = jQuery(this).attr('id');
                newDiv = jQuery('.'+newDiv);
                var t = 500;
                if(newDiv.text() != oldDiv.text())
                {
                    oldDiv.animate({
                        opacity: 0,
                        marginBottom:"-=200",
                        marginTop: "+=200px"
                    }, t, function(){
                        jQuery(this).css({'margin-top' : '0px', 'margin-bottom': '0px', 'display' : 'none', 'opacity' : 1});
                    });
//                    newDiv.delay(300).slideDown(600);
                    newDiv.delay(300).slideDown(1000, 'easeOutBounce');
                    oldDiv = newDiv;
                }
            });
        });

    });
</script>

<script type="text/javascript">
    jQuery(document).ready(function(){

        jQuery('.postStatus').click(function(){
            checkFormpostStatus();
        });

        function checkFormpostStatus()
        {
            jQuery('#formSubStatus').validate({
                errorElement: "span",
                rules: {
                    contentStatus : {
                        required:true
                    }
                },
                messages:{
                    contentStatus:{
                        required: "*.Cảm xúc của bạn là trống rỗng ?"
                    }
                },
                submitHandler : function(){
                    ajaxSubtmitPostStatus();
                }
            });
        }

        function ajaxSubtmitPostStatus()
        {
            var status = jQuery('#statusPostContent').val();
            alert(status);
            var data = "status="+status;

            jQuery.ajax({
                type: "POST",
                url: "<?php echo $this->url('success', array('action' => 'savestatus')); ?>",
                data: data,
                async:false,
                success: function(data) {
                    alert(data);
                    data = JSON.parse(data);
                    var success = data['success'];
                    var divError = jQuery('#statusPostContent span');
                    if(success == "1")
                    {
//                        alert('thanh cong');
                        divError.html(data['message']);
                        divError.show().delay(4000).fadeOut();
                    }
                    else
                    {
//                        alert('that bai');
                        divError.html(data['error']);
                        divError.fadeIn(600).delay(4000).fadeOut();
                    }
                },
                error: function() {
                    alert("Hệ thống đang bảo trì, xin hãy thử lại sau một ít phút nữa!");
                }
            });
            return false;
        }


    });
</script>