
<noscript>
    <style>
        .st-accordion ul li{
            height:auto;
        }
        .st-accordion ul li > a span{
            visibility:hidden;
        }
    </style>
</noscript>

<div class="container bg-update">
    <div class="wrapper">
        <div id="st-accordion" class="st-accordion">
            <ul>
                <li>
                    <a class="iconInfo" href="#"> I
                        <label>Thay đổi hình đại diện</label>
                        <span class="st-arrow">Open or Close</span>
                    </a>
                    <div class="st-content">
                       <div>
                           <div>
                               <label>Hình đại diện</label>
                               <img src="<?php echo $this->basePath();?>/img/1.jpg">
                               <input type="file" name="file" id="files">
                           </div>
                       </div>
                    </div>
                </li>
                <li>
                    <a class="iconInfo" href="#"> U
                        <label style="margin-left: 15px">Giới thiệu bản thân</label>
                        <span class="st-arrow">Open or Close</span>
                    </a>
                    <div class="st-content">
                        <form>
                            <div class="divAboutme">
                                <label>Trường học: </label>
                                <input type="text" placeholder="Nhập tên trường bạn đã học...">
                            </div>
                            <div class="divAboutme">
                                <label>Nơi làm việc: </label>
                                <input type="text" placeholder="Nhập nơi bạn đang làm việc...">
                            </div>
                            <div class="divAboutme">
                                <label>Tình trạng hôn nhân: </label>
                                <div class="select-wrapper">
                                    <select>
                                        <option value="">Chọn...</option>
                                        <option value="">Độc thân</option>
                                        <option value="">Đang hẹn hò</option>
                                        <option value="">Quan hệ mở</option>
                                        <option value="">Quan hệ phức tạp</option>
                                        <option value="">Đã kết hôn</option>
                                    </select>
                                </div>

                            </div>
                            <div class="divAboutme">
                                <label></label>
                                <button>Cập nhật</button>
                            </div>
                        </form>
                    </div>
                </li>
                <li>
                    <a class="iconInfo" href="#"> D
                        <label style="margin-left: 15px;">Thông tin cơ bản</label>
                        <span class="st-arrow">Open or Close</span>
                    </a>
                    <div class="st-content">
                        <p>O my friend - but it is too much for my strength - I sink under the weight of the splendour of these visions!</p>
                        <p>A wonderful serenity has taken possession of my entire soul, like these sweet mornings of spring which I enjoy with my whole heart.</p>
                        <p>I am alone, and feel the charm of existence in this spot, which was created for the bliss of souls like mine.</p>
                    </div>
                </li>
                <li>
                    <a class="iconInfo" href="#"> S
                        <label style="margin-left: 15px;">Cài đặt tài khoản</label>
                        <span class="st-arrow">Open or Close</span>
                    </a>
                    <div class="st-content">
                        <p>O my friend - but it is too much for my strength - I sink under the weight of the splendour of these visions!</p>
                        <p>A wonderful serenity has taken possession of my entire soul, like these sweet mornings of spring which I enjoy with my whole heart.</p>
                        <p>I am alone, and feel the charm of existence in this spot, which was created for the bliss of souls like mine.</p>
                    </div>
                </li>

            </ul>
        </div>
    </div>
</div>


<script type="text/javascript">
    $(document).ready(function(){
        $('#st-accordion').accordion();
    });

</script>