<section class="userInfo">
    <div class="info">
        <div class="userAvatar">
            <img alt="User Name" src="<?php echo $this->basePath().'/uploads/'.$useravatar; ?>" />
            <span><a href="#"><?php echo $userdata->getFirstName(). ' ' . $userdata->getLastName() ?></a></span>
        </div>
    </div>
    <div class="showMe">
        <p>Xem thông tin mới từ</p>
        <div class="btnShow friend"><span>Bạn bè</span></div>
        <div class="btnShow place"><span>Địa điểm</span></div>
    </div>
</section>

<section class="newsInfo">
    <div class="news friendNews">
        <div class="friendNews-block">
            <div class="friendNews-block-avatar">
                <img alt="User Name" src="<?php echo $this->basePath();?>/img/1.Avatar-200x200.jpg" />
                <span>John Smith</span>
            </div>
            <div class="friendNews-block-content">
                <div class="time-content">
                    <span>vừa đăng</span>
                </div>
                <div class="content-content">
                    <p>Hôm nay ngày gì mà lạnh thế ko biết :-S</p>
                </div>
                <div class="content-like-comment-share">
                    <a href="#">Thích</a>
                    <a href="#">Bình luận</a>
                    <a href="#">Chia sẻ</a>
                    <img src="images/star1.png"><span> 12 người thích điều này</span>
                </div>
            </div>
        </div>
        <div class="friendNews-block">
            <div class="friendNews-block-avatar">
                <img alt="User Name" src="<?php echo $this->basePath();?>/img/2.Avatar-200x200.jpg" />
                <span>Adam Culi</span>
            </div>
            <div class="friendNews-block-content">
                <div class="time-content">
                    <span>vào 10 phút trước</span>
                </div>
                <div class="content-content">
                    <p>Lạnh teo trYm rồi :((</p>
                </div>
                <div class="content-like-comment-share">
                    <a href="#">Thích</a>
                    <a href="#">Bình luận</a>
                    <a href="#">Chia sẻ</a>
                </div>
            </div>
        </div>
        <div class="friendNews-block">
            <div class="friendNews-block-avatar">
                <img alt="User Name" src="<?php echo $this->basePath();?>/img/3.Avatar-200x200.jpg" />
                <span>Peter Fever</span>
            </div>
            <div class="friendNews-block-content">
                <div class="time-content">
                    <span>vào 20 phút trước</span>
                </div>
                <div class="content-content">
                    <p>Chắc ngày mai có tuyết rơi =))</p>
                </div>
                <div class="content-like-comment-share">
                    <a href="#">Thích</a>
                    <a href="#">Bình luận</a>
                    <a href="#">Chia sẻ</a>
                </div>
            </div>
        </div>
        <div class="friendNews-block">
            <div class="friendNews-block-avatar">
                <img alt="User Name" src="<?php echo $this->basePath();?>/img/4.Avatar-200x200.jpg" />
                <span>Jean Charle</span>
            </div>
            <div class="friendNews-block-content">
                <div class="time-content">
                    <span>vào 2 tiếng trước</span>
                </div>
                <div class="content-content">
                    <p>Sắp tới Noel rồi, phải kiếm gấu thôi :"></p>
                </div>
                <div class="content-like-comment-share">
                    <a href="#">Thích</a>
                    <a href="#">Bình luận</a>
                    <a href="#">Chia sẻ</a>
                </div>
            </div>
        </div>
        <div class="friendNews-block">
            <div class="friendNews-block-avatar">
                <img alt="User Name" src="<?php echo $this->basePath();?>/img/4.Avatar-200x200.jpg" />
                <span>Jean Charle</span>
            </div>
            <div class="friendNews-block-content">
                <div class="time-content">
                    <span>vào 2 tiếng trước</span>
                </div>
                <div class="content-content">
                    <p>Sắp tới Noel rồi, phải kiếm gấu thôi :"></p>
                </div>
                <div class="content-like-comment-share">
                    <a href="#">Thích</a>
                    <a href="#">Bình luận</a>
                    <a href="#">Chia sẻ</a>
                </div>
            </div>
        </div>
    </div>
    <div class="news placeNews">
        <div class="placeNews-block">
            <div class="placeNews-block-avatar">
                <img alt="User Name" src="<?php echo $this->basePath();?>/img/5.Avatar-200x200.jpg" />
                <span>Yeah1 TV</span>
            </div>
            <div class="placeNews-block-content">
                <div class="time-content">
                    <span>vào 2 tiếng trước</span>
                </div>
                <div class="content-content">
                    <p>Giáng sinh đến rồi, hãy cùng Yeah1 trang trí ngôi nhà của mình nào nào :"></p>
                </div>
                <div class="content-like-comment-share">
                    <a href="#">Không thích</a>
                    <a href="#">Bình luận</a>
                    <a href="#">Chia sẻ</a>
                    <img src="<?php echo $this->basePath();?>/img/star1.png"><span> Bạn và 12 người thích điều này</span>
                </div>
            </div>
        </div>
        <div class="placeNews-block hashtag">
            <div class="placeNews-block-avatar">
                <img alt="User Name" src="<?php echo $this->basePath();?>/img/Avatar-200x200.jpg" />
                <span>Xu Bi</span>
            </div>
            <div class="placeNews-block-content">
                <div class="time-content">
                    <span>vào 2 tiếng trước</span>
                </div>
                <div class="content-content">
                    <div class="status-place-image">
                        <img src="<?php echo $this->basePath();?>/img/place-500x500.jpg">
                    </div>
                    <div class="status-place-name">
                        <span class="name">Hồ Chí Minh City</span><br>
                        <span class="hashtag">#ho_chi_minh_city</span>
                    </div>
                    <div class="status-place-des">
                        <p>Sài gòn, thành phố tôi yêu!! Sài gòn, thành phố tôi yêu!!Sài gòn, thành phố tôi yêu!! Sài gòn, thành phố tôi yêu!!Sài gòn, thành phố tôi yêu!! Sài gòn, thành phố tôi yêu!!Sài gòn, thành phố tôi yêu!! Sài gòn, thành phố tôi yêu!!</p>
                    </div>
                </div>
                <div class="content-like-comment-share">
                    <a href="#">Thích</a>
                    <a href="#">Bình luận</a>
                    <a href="#">Chia sẻ</a>
                    <img src="<?php echo $this->basePath();?>/img/star1.png"><span> 12 người thích điều này</span>
                </div>
            </div>
        </div>
    </div>
</section>

<section class="suggestion">
    <p>Có thể bạn sẽ quan tâm ;)</p>
    <div class="highlights place">
        <p>Các địa điểm nổi bật</p>
        <div class="place-place">
            <div class="place-place-avatar">
                <img src="<?php echo $this->basePath();?>/img/1.avatar-70x70.jpg" />
            </div>
            <div class="place-place-name">
                <a href="#" >Lẩu cá 44</a>
            </div>
            <div class="place-place-type">
                <span>Nhà hàng</span>
            </div>
            <div class="place-place-like-number">
                <span>300.000 lượt thích</span>
            </div>
        </div>
        <div class="place-place">
            <div class="place-place-avatar">
                <img src="<?php echo $this->basePath();?>/img/2.avatar-70x70.jpg" />
            </div>
            <div class="place-place-name">
                <a href="#" >Vườn nướng</a>
            </div>
            <div class="place-place-type">
                <span>Nhà hàng</span>
            </div>
            <div class="place-place-like-number">
                <span>300.000 lượt thích</span>
            </div>
        </div>
        <div class="place-place last">
            <div class="place-place-avatar">
                <img src="<?php echo $this->basePath();?>/img/3.avatar-70x70.jpg" />
            </div>
            <div class="place-place-name">
                <a href="#" >Cafe Sunshine</a>
            </div>
            <div class="place-place-type">
                <span>Nhà hàng</span>
            </div>
            <div class="place-place-like-number">
                <span>300.000 lượt thích</span>
            </div>
        </div>
    </div>
    <div class="highlights suggestion-place">
        <p>Các địa điểm mới</p>
        <div class="place-place">
            <div class="place-place-avatar">
                <img src="<?php echo $this->basePath();?>/img/4.avatar-70x70.jpg" />
            </div>
            <div class="place-place-name">
                <a href="#" > Bún chả cả</a>
            </div>
            <div class="place-place-type">
                <span>Nhà hàng</span>
            </div>
            <div class="place-place-like-number">
                <span>300.000 lượt thích</span>
            </div>
        </div>
    </div>
    <div class="highlights friend">
        <p>Có thể bạn biết</p>
        <div class="place-place">
            <div class="place-place-avatar">
                <img src="<?php echo $this->basePath();?>/img/5.avatar-70x70.jpg" />
            </div>
            <div class="place-place-name">
                <a href="#" >Adam Johnson</a>
            </div>
            <div class="place-place-type">
                <span>15 bạn chung</span>
            </div>
            <div class="place-place-like-number">
                <span>393 bạn</span>
            </div>
        </div>
    </div>
</section>

<footer class="footer">
    <div class="zess-logo">This is logo</div>
    <div class="search">
        <i class="icon-search"></i>
        <input type="text" placeholder="Search everything you want ...">
    </div>
    <div class="footer-menu">
        <div class="menu-home">
            Home
        </div>
        <div class="menu-me">
            Me
        </div>
    </div>
</footer>